### ISSUE TITLE
After upgrade from Zammad 2.5 to 2.6, LDAP sync no longer works.

### ISSUE THREAD

**Issue by killstrelok** [zammad/zammad#2196]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): package from zammad repo
* Operating system: CentOS 7
* Database + version: PostgreSql
* Elasticsearch version:
* Browser + version: Firefox but the issue persists across other browsers

### Expected behavior:

* After upgrade from Zammad 2.5 to 2.6, LDAP sync reports successful sync.

### Actual behavior:

* LDAP sync throws an error:
An error occurred: undefined method `with_indifferent_access' for nil:NilClass

I admit I didn't stop zammad's services before an upgrade. I've already tried this: https://github.com/zammad/zammad/issues/1245 to no avail. I restarted the server etc. and the problem persists.

**Comment by thorsteneckel** [comment]
Hi @killstrelok - This is a technical question because the error is probably caused by the problems in the update process. Could you please create a topic over at the [community board](http://community.zammad.org/) and add the whole log file (especially the traceback of the `undefined method 'with_indifferent_access' for nil:NilClass' class` error). Thanks!
