### ISSUE TITLE
undefined method `to_hash` on editing select fields in the admin interface after migration to 5.1

### ISSUE THREAD

**Issue by eeuak** [zammad/zammad#4027]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* https://github.com/zammad/zammad/issues/294

implemented in:
[Change Log 5.1.0](https://github.com/zammad/zammad/blob/5.1.0/CHANGELOG.md#510-2022-03-14)
 (2022-03-14)

### Actual behavior:

* After the Upgrade from a previous Zammad version (5.0 in my case)
* When trying to save object that was created before the upgrade with "Use custom option sort" selected -> Database update throws:

> undefined method `to_hash' for #<Array:0x0000563c766170e8>
Did you mean?  to_h

### Steps to reproduce the behavior:

* selection object that was created before the upgrade -> edit -> check "Use custom option sort" -> save -> "Database Update" -> error

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ozturkinc** [comment]
I do apologise if this should be in another questions/issue but I am getting a similar issue when trying to update a select object since upgrading to 5.1 as well:
**undefined method `update' for #<Array:0x00007f61a1539508>**
Just thought I would mention...

Thanks for all the hard work!

**Comment by rolfschmidt** [comment]
> I do apologise if this should be in another questions/issue but I am getting a similar issue when trying to update a select object since upgrading to 5.1 as well: **undefined method `update' for #Array:0x00007f61a1539508** Just thought I would mention...
> 
> Thanks for all the hard work!

Sure, could be related. Do you remember the steps which it takes to reproduce your error? Maybe you also can post the stacktrace error of your `log/production.log`. You should be able to find the error there and in which files the error is caused.

**Comment by rolfschmidt** [comment]
> I do apologise if this should be in another questions/issue but I am getting a similar issue when trying to update a select object since upgrading to 5.1 as well: **undefined method `update' for #Array:0x00007f61a1539508** Just thought I would mention...
> 
> Thanks for all the hard work!

@ozturkinc  There will be a bugfix available tomorrow. Maybe you can try to update your zammad **tomorrow** and see if your bug is fixed as well. Else please let me know and provide more infos.

**Comment by ozturkinc** [comment]
@rolfschmidt I have tried to reproduce the error but instead now I am getting the "to_hash" error reported originally rather than "update". I can't remember the exact steps I took at the time so hopefully tomorrows update will fix everything :)
