### ISSUE TITLE
Error creating ticket with changed Ticket Number Format

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#228]
If i change settings "Ticket Number Format" from Increment to Date i get the follwoing error when trying to add a new ticket:

> StatusCode: 500
> {"error":"undefined method `[]' for false:FalseClass"}

**Comment by monotek** [comment]
Works in 1.1. if only Ticket Number Format is changed.

After als changing:

Ticket Number Increment Date
Ticket Number Increment

I got the old error. Even if i changed the last 2 options to the old values.

**Comment by martini** [comment]
JFI, duplicate of https://github.com/zammad/zammad/issues/413, fix is on the way.
