### ISSUE TITLE
Zendesk Import > Undefined Method "log" on ticket import

### ISSUE THREAD

**Issue by PhilippSchreiber** [zammad/zammad#1328]
### Infos:

* Used Zammad version: 1.5.0-1501408728.d0ac4461.xenial
* Used Zammad installation source: ubuntu package
* Operating system: Ubung 16.04 LTS
* Browser + version: Chrome 59.0.3071.115  

### Expected behavior:

* Import all Groups, Organizations, Users and Tickets

### Actual behavior:

* Imports all Groups, Organizations, Users but not Tickets
* Throws the following error:

`undefined method `log' for #<Import::Zendesk::Ticket::Comment::Attachment:0x007faa218b0088>↵Did you mean?  loop`

* The number of tickets is not valid (actual there are > 30.000 tickets)

### Steps to reproduce the behavior:

* Start import on our system and wait for a long time

![image](https://user-images.githubusercontent.com/1312725/29017331-b19af6e8-7b56-11e7-8bb2-7f5c61cf27d2.png)

**Comment by thorsteneckel** [comment]
Hi @PhilippSchreiber ! Thanks for reporting this. I'm currently at another issue with is more or less a duplicate of this: https://github.com/zammad/zammad/issues/1161#issuecomment-311911559

It also has the issue with more than 1.000 tickets and the broken attachments file. A fixed version of the attachment file with a text how to apply can be found there. I'm still working on the > 1.000 tickets issue.

As far as I can tell the the import works but doesn't show the right progress. So if you wait long enough and check the log file for the end of the import the system is usable. However this is not the desired behavior. I'm working on a fix.

**Comment by PhilippSchreiber** [comment]
Thanks @thorsteneckel for the fast answer. Should I apply both fixes from #1161 ?

**Comment by thorsteneckel** [comment]
Yes! State and Attachment.

**Comment by PhilippSchreiber** [comment]
OK, import is running and it will take ~5 hours. I will report back when it's done.

**Comment by PhilippSchreiber** [comment]
OK, the fix worked. Unfortunately the import ran > 30h. I will open another issue on that.

**Comment by thorsteneckel** [comment]
Hi @PhilippSchreiber - Thanks for your feedback. Please note that we already did some performance analyses for [this here](https://github.com/zammad/zammad/issues/558#issuecomment-272428884). So I think there is little we can do 😞
