### ISSUE TITLE
Import unprocessed Emails

### ISSUE THREAD

**Issue by christianreiss** [zammad/zammad#4641]
### Used Zammad Version

6.0

### Environment

- Installation method: package
- Operating system: AlmaLinux 8
- Database + version:  postgresql-10.23-1
- Elasticsearch version: elasticsearch-7.17.10-1
- Browser + version: many

### Actual behaviour

```
$  zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/58553990bc2a11bf09720547d513eed0.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `match?' for nil:NilClass\n\n    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})\n                    ^^^^^^^>"
/opt/zammad/app/models/channel/email_parser.rb:141:in `rescue in process': #<NoMethodError: undefined method `match?' for nil:NilClass (RuntimeError)

    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})
                    ^^^^^^^>
/opt/zammad/app/models/channel/filter/identify_sender.rb:172:in `populate_attributes!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:156:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
/opt/zammad/app/models/channel/email_parser.rb:165:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:162:in `each'
/opt/zammad/app/models/channel/email_parser.rb:162:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:126:in `block in process'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:125:in `process'
/opt/zammad/app/models/channel/email_parser.rb:511:in `block in process_unprocessable_mails'
<internal:dir>:220:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:510:in `process_unprocessable_mails'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/zammad/bin/rails:5:in `<main>'
	from /opt/zammad/app/models/channel/email_parser.rb:123:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:511:in `block in process_unprocessable_mails'
	from <internal:dir>:220:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:510:in `process_unprocessable_mails'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/bin/rails:5:in `<main>'
/opt/zammad/app/models/channel/filter/identify_sender.rb:172:in `populate_attributes!': undefined method `match?' for nil:NilClass (NoMethodError)

    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})
                    ^^^^^^^
	from /opt/zammad/app/models/channel/filter/identify_sender.rb:156:in `user_create'
	from /opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
	from /opt/zammad/app/models/channel/email_parser.rb:165:in `block in _process'
	from /opt/zammad/app/models/channel/email_parser.rb:162:in `each'
	from /opt/zammad/app/models/channel/email_parser.rb:162:in `_process'
	from /opt/zammad/app/models/channel/email_parser.rb:126:in `block in process'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
	from /opt/zammad/app/models/channel/email_parser.rb:125:in `process'
	from /opt/zammad/app/models/channel/email_parser.rb:511:in `block in process_unprocessable_mails'
	from <internal:dir>:220:in `glob'
	from /opt/zammad/app/models/channel/email_parser.rb:510:in `process_unprocessable_mails'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/zammad/bin/rails:5:in `<main>'
```

### Expected behaviour

Unprocessed Emails get imported / processed.

### Steps to reproduce the behaviour

I am not sure if it can be reproduced or if is only me.
Seems like a missing module?

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by areto** [comment]
Hi, 
i have i similar Problem. After i updated my LXC Container to 6.0 yesterday i'm not able to fetch Mails and update Tickets.
`I, [2023-06-07T08:35:19.226643#698-122600]  INFO -- : Started PUT "/api/v1/tickets/26525?all=true" for 10.1.255.243 at 2023-06-07 08:35:19 +0200
I, [2023-06-07T08:35:19.230537#698-122600]  INFO -- : Processing by TicketsController#update as JSON
I, [2023-06-07T08:35:19.230594#698-122600]  INFO -- :   Parameters: {"number"=>"1726460", "title"=>"Fwd:Lizenz", "group_id"=>"1", "owner_id"=>"1531", "customer_id"=>14, "state_id"=>"4", "priority_id"=>"2", "article"=>{"from"=>"XXX", "to"=>"XXX", "cc"=>"", "subject"=>"", "body"=>"[FILTERED]", "content_type"=>"text/html", "ticket_id"=>26525, "type_id"=>1, "sender_id"=>1, "internal"=>false, "in_reply_to"=>"<XXX>", "form_id"=>"119664388", "subtype"=>"reply"}, "updated_at"=>"2023-06-05T10:11:21.683Z", "preferences"=>{"channel_id"=>3, "escalation_calculation"=>{"last_update_at"=>"2023-06-05T10:11:21.550Z", "last_contact_at"=>"2023-06-05T10:11:21.550Z", "sla_id"=>5, "sla_updated_at"=>"2019-02-01T15:13:30.572Z", "calendar_id"=>2, "calendar_updated_at"=>"2023-06-05T09:01:28.823Z", "escalation_disabled"=>false}}, "organization_id"=>2, "pending_time"=>nil, "id"=>"26525", "all"=>"true"}
E, [2023-06-07T08:35:19.326982#698-122600] ERROR -- : undefined method `name' for #<EmailAddress id: 1, channel_id: 3, realname: "IT", email: "XXX", active: true, note: nil, preferences: nil, updated_by_id: 5, created_by_id: 5, created_at: "2018-11-20 18:11:57.171859000 +0000", updated_at: "2018-11-20 18:11:57.171000000 +0000"> (NoMethodError)`

**Comment by mantas** [comment]
@areto in your case, it looks like migrations didn't run. `email_addresses.realname` was renamed to `email_addresses.name`. But this is a different issue than the one reported by Christian.

**Comment by fliebe92** [comment]
Hey @christianreiss, could you please attach the mail that caused the issue for you? Otherwise, there is no chance to verify the reported behavior.

Thanks a lot. 😎

**Comment by areto** [comment]
Thank you @mantas i migrated and upgraded ruby to 3.1.3. Now everything is fine.

**Comment by fliebe92** [comment]
Closing for now due to no feedback. Feel free to provide more information and I'm happy to reopen this issue.

**Comment by christianreiss** [comment]
Sorry -- that went of my radar.

I have 8 possible emails, but since they are real life company emails I can not make them publicly available.
I could anonyminize them and send one or two to you in person.

**Comment by fliebe92** [comment]
> Sorry -- that went of my radar.
> 
> I have 8 possible emails, but since they are real life company emails I can not make them publicly available. I could anonyminize them and send one or two to you in person.

Feel free to send them to support@zammad.com and mention this issue here, with a note that it should be handed over to me. Thanks!

**Comment by fliebe92** [comment]
Hi @christianreiss,

I had some time now to check your examples - thanks for sending them!

There is only one mail that was imported without any issues to my local test machine - the rest fails due to not having a proper `From` part. If I put a dummy `From: dummy@example.com` in it, it works like a charm.

Can you please check why those emails do not contain any `From: ...`?
