### ISSUE TITLE
6.3.1: agent notification broken when French language is used (NoMethodError)

### ISSUE THREAD

**Issue by jouvin** [zammad/zammad#5316]
### Used Zammad Version

6.3.1

### Environment

- Installation method: [e.g. source, package]: RPM
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]: AlmaLinux 8
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]: postgresql 14
- Elasticsearch version: [e.g. 7.17]: 8.14
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]: Opera 112 (but irrelevant, happens with all browsers)

### Actual behaviour

Since upgrade to 6.3.1, notifications of group agents when the customer makes a change to the ticket are broken. For each of them, there is an entry like:

```
E, [2024-08-28T11:53:01.645380#1199186-149120] ERROR -- : undefined method `present ?' for {"State"=>["ouvert", "clos"]}:Hash (NoMethodError)
```
Other notifications (customer notification after an agent action) work well. Also the notification when a new ticket is created if properly sent to all group agents.

After some troubleshooting, we found it was caused by non-ASCII characters at the end of the `present` method name in `/opt/zammad//app/views/mailer/ticket_update/fr.html.erb` when testing for the presence of a ticket change ([see screen shot](https://github.com/user-attachments/assets/7fce2442-0c07-4fd7-a6ca-0e01a9f46be1) as the character is not printable). The same character is present in 3 other lines but it doesn't prevent the notification to work. Removing the character was enough to fix the problem.

The same problem seems to exist also in `/opt/zammad/app/views/messaging/ticket_update/fr.md.erb` which does not seem to used in our instance.

This non-ASCII character (and thus the problem) seems to be present only in the `fr` version, AFAICT.

### Expected behaviour

Notifications to work in both directions.

### Steps to reproduce the behaviour

1. Configure Zammad instance to use French locale
2. Create a ticket
3. Have the agent answering the ticket
4. Ask the customer to update the ticket

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
@jouvin we had a similar report recently with #5218, where the wrong French translation in the template was fixed. Can you please update to the latest build of Zammad 6.3.1 (latest `stable`)? Then it should work again.

See https://github.com/zammad/zammad/blob/stable/app/views/mailer/ticket_update/fr.html.erb

Closing as duplicate of #5218

**Comment by jouvin** [comment]
Thanks! Sorry for missing the duplicate but from the description/title it was not obvious it was related. BTW, I used the last RPM I found for EL8 (we sync the repo every day), `zammad-6.3.1-1718095957.bfe18b8e.centos8.x86_64.rpm` from June 13 that does not seem to have the fix, thus my report. We are about to use the EL9 version that seems to have more recent RPM versions, hopefully the fix is in.

**Comment by mgruner** [comment]
@jouvin there are very recent builds for `stable`: https://packager.io/gh/zammad/zammad/refs/stable

If the repo does not reflect them, there might be an issue. Or do you use some mirror?

**Comment by jouvin** [comment]
I mirror https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/8/x86_64 and our sync script has not picked up any new RPM since Jun. 13 despite it runs everyday. I don't think the problem is in our sync script that is used for many repos successfully, including Zammad.
