### ISSUE TITLE
Job BackgroundJobSearchIndex NoMethodError: undefined method `lookup' for User::Permission:Module

### ISSUE THREAD

**Issue by bc1000** [zammad/zammad#1424]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) package
* Operating system: CentOS Linux release 7.3.1611 (Core)
* Browser + version: 

### Expected behavior:

* 

### Actual behavior:

* 

### Steps to reproduce the behavior:

* I see a lot of ERROR messages in production.log since update to 2.0
```
I, [2017-09-15T08:53:45.881604 #7003]  INFO -- : 2017-09-15T08:53:45+0200: [Worker(host:** pid:7003)] Job BackgroundJobSearchIndex (id=18015) RUNNING
E, [2017-09-15T08:53:45.893326 #7003] ERROR -- : 2017-09-15T08:53:45+0200: [Worker(host:**l pid:7003)] Job BackgroundJobSearchIndex (id=18015) FAILED (3 prior attempts) with NoMethodError: undefined method `lookup' for User::Permission:Module
I, [2017-09-15T08:53:45.897133 #7003]  INFO -- : 2017-09-15T08:53:45+0200: [Worker(host:**l pid:7003)] Job BackgroundJobSearchIndex (id=18017) RUNNING
E, [2017-09-15T08:53:45.902413 #7003] ERROR -- : 2017-09-15T08:53:45+0200: [Worker(host:**l pid:7003)] Job BackgroundJobSearchIndex (id=18017) FAILED (3 prior attempts) with NoMethodError: undefined method `lookup' for User::Permission:Module
```

**Comment by thorsteneckel** [comment]
Hi @bc1000 - can you please run `Delayed::Job.where.not(last_error: nil)` on your [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) and post the result here?

**Comment by bc1000** [comment]
zammad run rails c
Loading production environment (Rails 4.2.9)
irb(main):001:0> Delayed::Job.where.not(last_error: nil)
=> #<ActiveRecord::Relation [#<Delayed::Backend::ActiveRecord::Job id: 18028, priority: 0, attempts: 6, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 07:30:25", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:51:38", updated_at: "2017-09-15 07:08:44">, #<Delayed::Backend::ActiveRecord::Job id: 17945, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17950, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17956, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17962, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17968, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17974, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17980, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17943, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, #<Delayed::Backend::ActiveRecord::Job id: 17944, priority: 0, attempts: 7, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "undefined method `lookup' for User::Permission:Mod...", run_at: "2017-09-15 08:04:35", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2017-09-15 06:45:40", updated_at: "2017-09-15 07:24:29">, ...]>
irb(main):002:0>

**Comment by bc1000** [comment]
I installed elasticsearch this morning, about 08:10
I updated to 2.0 about 08:40
I also had to change index_name, sess https://github.com/zammad/zammad/issues/1215

**Comment by thorsteneckel** [comment]
Thanks for your fast response! Can you please do it again with `Delayed::Job.where.not(last_error: nil).first.last_error`.

**Comment by bc1000** [comment]
zammad run rails c
Loading production environment (Rails 4.2.9)
irb(main):001:0> Delayed::Job.where.not(last_error: nil).first.last_error
=> "undefined method `lookup' for User::Permission:Module\n/opt/zammad/app/models/user/search_index.rb:24:in `block in search_index_attribute_lookup'\n/opt/zammad/app/models/user/search_index.rb:23:in `each'\n/opt/zammad/app/models/user/search_index.rb:23:in `search_index_attribute_lookup'\n/opt/zammad/app/models/concerns/has_search_index_backend.rb:60:in `search_index_update_backend'\n/opt/zammad/lib/background_job_search_index.rb:11:in `perform'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'\n/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\n/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'\n/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'\n/opt/zammad/app/models/scheduler.rb:239:in `block (3 levels) in worker'\n/opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\n/opt/zammad/app/models/scheduler.rb:237:in `block (2 levels) in worker'\n/opt/zammad/app/models/scheduler.rb:233:in `loop'\n/opt/zammad/app/models/scheduler.rb:233:in `block in worker'\n/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"
irb(main):002:0>

**Comment by thorsteneckel** [comment]
Hi @bc1000 - Thanks for your support and fast response time. This issue is fixed. You can update your package in ~30 minutes from now. Feedback is welcome.
