### ISSUE TITLE
Frontend: "Uncaught TypeError: this.addDeletedOptions is not a function" after upgrade to 5.2.3

### ISSUE THREAD

**Issue by alxndr42** [zammad/zammad#4286]
I just upgraded our source code installation from 5.0.3 to 5.2.3 following the [upgrade instructions](https://docs.zammad.org/en/latest/install/update.html#source-update), and now the frontend is no longer showing tickets in Overviews or individually.

The browser console shows this error message:

> Uncaught TypeError: this.addDeletedOptions is not a function application-87b0edaf374a9d53c8840d55eb9d81dea3bbdcafe8625d91b005095aff33a366.js:44

I tried `rake assets:clean` and then `rake assets:precompile` again, which didn't help.

### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): Source code upgrade from 5.0.3
* Operating system: Ubuntu 20.04
* Database + version: PostgreSQL 10
* Elasticsearch version: None
* Browser + version: Firefox 105

### Expected behavior:

* Overviews show lists of tickets
* Individual tickets open with content

### Actual behavior:

* Overviews are empty
* Individual tickets open empty

### Steps to reproduce the behavior:

* Perform a source code upgrade from 5.0.3 to 5.2.3

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by alxndr42** [comment]
Updating from 5.0.3 to 5.1.1 and then to 5.2.3 seems to do the trick. Not sure why the intermediate step was necessary (the documentation doesn't seem to state this is necessary), but our installation shows tickets again.

**Comment by PabloCastellano** [comment]
Oh I ran into the same error today. Upgraded from 5.0.x to 5.2.3 and now my frontend is broken.

Please add some warning in the install notes!

**Comment by MrGeneration** [comment]
> Oh I ran into the same error today. Upgraded from 5.0.x to 5.2.3 and now my frontend is broken.
> 
> Please add some warning in the install notes!

For a percentile of 2 whopping instances? Nah.
