### ISSUE TITLE
Invalid `null` value for user's last name

### ISSUE THREAD

**Issue by cortopy** [zammad/zammad#3488]
### Infos:

* Used Zammad version: 4.0.0
* Installation method (source, package, ..): helm chart
* Operating system: Kubernetes
* Database + version: default in helm chart
* Elasticsearch version: default in helm chart
* Browser + version: n/a

### Expected behavior:

Creating a user via API with a last name `null` doesn't have unexpected side effects. It seems that the server should either:

- default the last name value to empty string
- not allow null value for last name

### Actual behavior:

If I create a user via the API with null last name, the server doesn't know how to handle certain situations and errors

### Steps to reproduce the behavior:

1. Create user in API with this payload:

```json
{
  "firstname": "John",
  "lastname": null,
  "email": "john@example.com"
}
```

2. Response will be:

```json
{
  ...
  "lastname": null
}
```

3. Try to delete user
4. I get error 

```json
{"error":"undefined method `length' for nil:NilClass"}
```

5. Manually add a surname
6. I can now delete the user

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hello @cortopy 

can you add your `log/production.log` (at least the related area) to this issue?

Thanks!

**Comment by cortopy** [comment]
This is a kubernetes installation and the logs used to be available `/opt/zammad/log/production.log`. However, since I upgraded to 4.0.0 there are no logs. Is there anywhere I can check?

**Comment by rolfschmidt** [comment]
Hi,
i can reproduce it. It was not clear that he tried to delete the user via web interface.

Steps to reproduce:

1. add user:

`curl -u master@example.com:test -H "Content-Type: application/json" -X POST -d '{ "firstname": "John", "lastname": null, "email": "john@example.com" }' http://ubuntu-rs:3000/api/v1/users`

2. open user profile in frontend

3. delete user via menu 

4. get redirected to data privacy interface

![grafik](https://user-images.githubusercontent.com/5445062/113263610-4696af80-92d2-11eb-9575-d2c080eae4a5.png)

**Comment by rolfschmidt** [comment]
traceback:

```
, [2021-04-01T09:11:08.506421 #3675-47304707523680] ERROR -- : undefined method `length' for nil:NilClass (NoMethodError)
/workspace/git_zammad/zammad/lib/pseudonymisation.rb:36:in `of_string'
/workspace/git_zammad/zammad/lib/pseudonymisation.rb:14:in `rescue in of_value'
/workspace/git_zammad/zammad/lib/pseudonymisation.rb:11:in `of_value'
/workspace/git_zammad/zammad/lib/pseudonymisation.rb:7:in `block in of_hash'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/hash_with_indifferent_access.rb:320:in `transform_values!'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/hash_with_indifferent_access.rb:320:in `block in transform_values'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/hash_with_indifferent_access.rb:320:in `tap'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/hash_with_indifferent_access.rb:320:in `transform_values'
/workspace/git_zammad/zammad/lib/pseudonymisation.rb:6:in `of_hash'
/workspace/git_zammad/zammad/app/models/data_privacy_task.rb:81:in `prepare_deletion_preview_anonymize'
/workspace/git_zammad/zammad/app/models/data_privacy_task.rb:58:in `prepare_deletion_preview'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:605:in `catch'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:199:in `block in halting'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `each'
/home/ubuntu-rs/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:513:in `invoke_before'

```

**Comment by MrGeneration** [comment]
Sounds like a regression. Didn't we have "empty lastname" issues already?

**Comment by rolfschmidt** [comment]
Looks like there is an issue with the Pseudonymisation of the user which is not able to handle null correctly... i will prepare a fix
