### ISSUE TITLE
Inline images are not working anymore

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1755]
### Infos:

* Used Zammad version: 2.2.0-1516200812.db19f309.centos7 / 2.3.0-something / 2.3.0-1516213604.33c09ee2.xenial
* Installation method (source, package, ..): package
* Operating system: CentOS7 / CentOS7 / Ubuntu 16.04
* Database + version: PostgreSQL-9.2.23 / PostgreSQL-9.2.23 / PostgreSQL-9.5
* Elasticsearch version:
* Browser + version: Newest Chromium & Firefox

### Expected behavior:

* When I copy & paste an image into an answer, the image should be displayed.

### Actual behavior:

* When I copy & paste an image into an answer, absolutely nothing happens.

### Steps to reproduce the behavior:

* Setup a fresh installed Zammad and try to paste an image inside an answer and see if something happens.

Additional infos:
I saw that inline images should work, so I tried it.
After it doesn't work on my 2.2.0 instance (where I tried a lot of different things, thought: maybe something was broke), I tried it on my 2.3.0 instance and it worked fine.
Unfortunately my 2.3.0 instance got broke and I tried the same on a fresh installed zammad 2.3.0 on my Ubuntu PC. There it doesn't work too.
I checked the production.log and there is also absolutely nothing

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by efernau** [comment]
same here, and if I use the API like in documetation, I get the base64 as a text message and not as an image.

**Comment by martini** [comment]
Hi @moellert 

> When I copy & paste an image into an answer, absolutely nothing happens.

I can't reproduce it (it's working fine). It there anything in the browser console log?

@efernau API issues should be handled in a different issue. Also you payload is required to reproduce it.

**Comment by moellert** [comment]
Hi @martini, the Firefox browser console on my Ubuntu 16.04 just says the following on both versions 2.2 & 2.3:
GET https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Leopardo_nel_Serengeti._Tanzania.jpg/1920px-Leopardo_nel_Serengeti._Tanzania.jpg 
[HTTP/2.0 304 Not Modified 26ms]
TypeError: a.text is not a function  application-8d6883f09eb040f4c553eccd35fdffc04fad82843ac037452d5317ba22e3c9fe.js:17:23889

I tested it also on my MacBook with Google Chrome and Safari, there I do the same and there is just the url pasted in the answer field and not the picture(it works everywhere else, Zimbra, Office, etc.)

**Comment by thorsteneckel** [comment]
Duplicate of #1376
