### ISSUE TITLE
report page doesn't work anymore (elasticsearch need to be configured) / SQL backend for reporting

### ISSUE THREAD

**Issue by driebe** [zammad/zammad#471]
Hi everyone,

so as some may already know, I am running a Zammad test environment on a Raspberry Pi3 with Rasbian. I had a stable 1.0 running for some weeks and updated my installation to 1.2.) here on git. It worked perfectly with only one slight glitch: When trying to open the report page (http://zammadpi/#report) I get an error message telling me that "Elasticsearch need to be configured!".

So far I thought installing elasticsearch is optional. Is that not the case anymore with version 1.2.? What do I need to do to get this either reversed or fixed?

Best regards
Daniel

**Comment by driebe** [comment]
After the instance now ran for the whole day, finally some error message manifested. Loading either dashboard or overview, the following error message appears:

`StatusCode: 500
{"error":"undefined method `each' for nil:NilClass"}`

Tickets from the activity stream can be opened, edited and saved fine. The settings page also functions normally. 

Though I am unsure of this message has something to do with a change in the ticket objects (yes I updated the database and restarted the system)... I tried adding a "type" object (I didn't see that there was a standard item called "type" already). Saving my new object didn't result in a error message or something. However, even after deleting the "type" object again the error message from above does not dissapear...

**Comment by driebe** [comment]
So after reinstalling the whole environment, the issue stays the same. But now I actually get an error message telling me that "Elasticsearch need to be configured!".

So far I thought installing elasticsearch is optional. Is that not the case anymore with version 1.2.? What do I need to do to get this either reversed or fixed?

**Comment by martini** [comment]
Hi Daniel,

> So far I thought installing elasticsearch is optional. Is that not the case anymore with version 1.2.? What do I need to do to get this either reversed or fixed?

The reporting page was not working in 1.0 without elasticsearch, this is the reason why now the "elasticsearch need to be configured" message is there.

-> For the reporting page we use grand elasticsearch features to have really powerful response.  

-=> So basically it's the same as it was in 1.0, just now without an error message but with a "need to be configured" message.

Anyway, for small installations small reporting could also be done via SQL - currently there not so much feedback about this needs. On your test environment reporting would be a no go?

 -Martin

PS: If you you Zammad in production I really like the powerful search (also in attachment) with gigabytes of data in just so less time.

**Comment by stefanhirt** [comment]
@martini
I would love to give you feedback about the reports, but I didn't find them in zammad.
If I try to open Zammd-URL\#report I only get an empty Main-Window in zammad.
I've seen in the zammad code that a user needs the requiredPermission: 'report', but where to set it?

**Comment by martini** [comment]
Hi @stefanhirt 

the reporting is not available in package installation, because if's not official released right now. 

-=> You can see it if you install develop branch from source.

It will look like this:

![screencapture-support-zammad-1480523996710](https://cloud.githubusercontent.com/assets/110226/20772903/b8ee4c18-b74f-11e6-8221-96bb1bee3c90.png)

 -Martin

**Comment by driebe** [comment]
Thanks for the information, closing this ticket since it is not a bug then.
