### ISSUE TITLE
Status Code 500 after upgrade to 2.0 ({"error":"undefined method `each' for nil:NilClass"})

### ISSUE THREAD

**Issue by TheRich-71** [zammad/zammad#1477]
### Infos:

* Used Zammad version: 2.0.0-1505468213.c4ce1caa.jessie
* Used Zammad installation source: (source, package, ...) debian package
* Operating system: Debian 8.9
* Browser + version: Firefox 55.0.3

After upgrading from zammad 1.5 to 2.0 and solving previously reported issue #1470 I am still not able to use zammad: After entering credentials at the login page, I get
> StatusCode: 500
> {"error":"undefined method `each' for nil:NilClass"}

Please find the relevant part from production.log attached. I would be happy if you can guide me to bring this system back to work...
[production.log](https://github.com/zammad/zammad/files/1332168/production.log)

**Comment by martini** [comment]
Hi @TheRich-71 

> > StatusCode: 500
> > {"error":"undefined method `each' for nil:NilClass"}

> Please find the relevant part from production.log attached. I would be happy if you can guide me to bring this system back to work...

## Background: 
With Zammad 2.0 a new role management has been introduced (https://zammad.com/business-features/role-management). For this we have changed the role module.

Your error message "{"error":"undefined method `each' for nil:NilClass"}" is because Zammad is still using an old cache (where the role model has the old structure).

In the update procedure your should stop Zammad first, update the package and start Zammad again.

It seems that Zammad was still running whiling updating (Zammad was erasing the Cache but another process was still running and writing the old cache format).

## Solution:
1) sudo systemctl stop zammad
2) zammad run rails r "Cache.clear"
3) sudo systemctl start zammad

And all should work fine again.

Feedback is welcome!

**Comment by TheRich-71** [comment]
Thanks, worked perfectly...

**Comment by martini** [comment]
@TheRich-71 thanks for feedback!
