### ISSUE TITLE
ldap import fails after migration from 2.5 to 2.6

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#2190]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: postgresql
* Elasticsearch version:
* Browser + version: Safari

### Expected behavior:

* LDAP Impot is working

### Actual behavior:

* ldap import fails

### Steps to reproduce the behavior:

* tbd

getting this error during ldap import job after migrating from 2.5 to 2.6. already tried to reconfigure ldap, that doesn't solve the problem as it is getting the same error on last step of config.

```
E, [2018-08-15T08:28:31.405635 #30345] ERROR -- : ImportJob 'Import::Ldap' failed: undefined method `with_indifferent_access' for nil:NilClass

E, [2018-08-15T08:28:31.405788 #30345] ERROR -- : undefined method `with_indifferent_access' for nil:NilClass (NoMethodError)
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @maggusf - there should be a traceback below this error lines that shows where the request comes from (file paths). Could you please provide those?

**Comment by maggusf** [comment]
of course:
```
E, [2018-08-15T08:28:31.405635 #30345] ERROR -- : ImportJob 'Import::Ldap' failed: undefined method `with_indifferent_access' for nil:NilClass
E, [2018-08-15T08:28:31.405788 #30345] ERROR -- : undefined method `with_indifferent_access' for nil:NilClass (NoMethodError)
/opt/zammad/lib/sequencer.rb:36:in `log_level_for'
/opt/zammad/lib/sequencer.rb:96:in `log_level'
/opt/zammad/lib/sequencer.rb:69:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:15:in `process'
/opt/zammad/lib/import/integration_base.rb:98:in `start'
/opt/zammad/app/models/import_job.rb:24:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/performable_method.rb:26:in `perform'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:355:in `block (3 levels) in worker'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:353:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:349:in `loop'
/opt/zammad/app/models/scheduler.rb:349:in `block in worker'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-08-15T08:28:31.423551 #30345]  INFO -- : 2018-08-15T08:28:31+0200: [Worker(host:zammad pid:30345)] Job ImportJob#start (id=3688443) COMPLETED after 0.09
28
```

**Comment by thorsteneckel** [comment]
Looks like the Migrations to 2.6 haven't been run (completely). Could you please stop all your Zammad services and execute `zammad run rake db:migrate`. If there is an error please post it here. Otherwise restart your Zammad and let us now.

**Comment by maggusf** [comment]
looks fine for me:
```
zammad run rake db:migrate
== 20180518100316 EmailForwardPrefixSettingIssue1730: migrating ===============
== 20180518100316 EmailForwardPrefixSettingIssue1730: migrated (0.0975s) ======

== 20180611070839 AddUxFlowNextUpToMacros: migrating ==========================
-- add_column(:macros, :ux_flow_next_up, :string, {:default=>"none", :null=>false})
   -> 0.1784s
== 20180611070839 AddUxFlowNextUpToMacros: migrated (0.1893s) =================

== 20180622140531 SequencerLogLevelSetting: migrating =========================
== 20180622140531 SequencerLogLevelSetting: migrated (0.0562s) ================

== 20180709020509 AddGroupDirectionToOverviews: migrating =====================
-- add_column(:overviews, :group_direction, :string, {:limit=>250, :null=>true})
   -> 0.0059s
== 20180709020509 AddGroupDirectionToOverviews: migrated (0.0074s) ============

== 20180711080554 Issue2100Utf8EncodeHttpLogs: migrating ======================
== 20180711080554 Issue2100Utf8EncodeHttpLogs: migrated (0.0531s) =============

== 20180719033247 AddConfidentialToDoorkeeperApplication: migrating ===========
== 20180719033247 AddConfidentialToDoorkeeperApplication: migrated (0.0029s) ==

== 20180809000001 CtiGenericApi: migrating ====================================
-- add_column(:cti_logs, :queue, :string, {:limit=>250, :null=>true})
   -> 0.0070s
-- add_column(:cti_logs, :initialized_at, :string, {:limit=>250, :null=>true})
   -> 0.0009s
-- add_column(:cti_logs, :duration_waiting_time, :integer, {:null=>true})
   -> 0.0007s
-- add_column(:cti_logs, :duration_talking_time, :integer, {:null=>true})
   -> 0.0006s
-- rename_column(:cti_logs, :start, :start_at)
   -> 0.0150s
-- rename_column(:cti_logs, :end, :end_at)
   -> 0.0045s
== 20180809000001 CtiGenericApi: migrated (0.0364s) ===========================
```

**Comment by maggusf** [comment]
and ldap synch is working again. thanks!

**Comment by ghost** [comment]
me too! Thanks!
