### ISSUE TITLE
Error 500 after upgrading to 1.2.0 (existing Taskbar entries in DB)

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#638]
### Infos:

* Used Zammad version: 1.2.0 (deb)
* Operating system: ubuntu 16.04
* Browser + version: FF 50.1.0

### Expected behavior:

* Smooth upgrade to 1.2.0 

### Actual behavior:

* Error 500 when logging into the upgraded system
```
Processing by TaskbarController#update as JSON 
  Parameters: {"key"=>"Ticket-77", "client_id"=>"123", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>77, "overview_id"=>9, "init"=>true}, "prio"=>3, "notify"=>false, "active"=>false, "updated_at"=>"2017-01-17T14:25:48.982Z", "id"=>"92", "taskbar"=>{"id"=>"92", "client_id"=>"123", "key"=>"Ticket-77", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>77, "overview_id"=>9, "init"=>true}, "prio"=>3, "notify"=>false, "active"=>false, "updated_at"=>"2017-01-17T14:25:48.982Z"}} 
undefined method `[]=' for nil:NilClass 
["/opt/zammad/app/models/taskbar.rb:58:in `update_preferences_infos'"
```

### Steps to reproduce the behavior:

* Make sure a user has open Ticket Tabs (Taskbars)
* Upgrade to 1.2.0
* Log into the upgraded system

### Quick fix

* Clear taskbars table in DB after upgrade

**Comment by martini** [comment]
JFI: Strange rails behaviour. Didn't have this problem. But seems to be fixed only with condition.
